# Generated by Django 5.2.5 on 2025-08-24 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0003_alter_cartitem_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderStatusUpdate',
        ),
        migrations.DeleteModel(
            name='OrderTracking',
        ),
    ]
